//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SrvControlPanel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SrvControlPanel.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fulanito, perenganito.
        /// </summary>
        internal static string msg090 {
            get {
                return ResourceManager.GetString("msg090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdkljfh sdljfh.
        /// </summary>
        internal static string msg091 {
            get {
                return ResourceManager.GetString("msg091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lskdjfh.
        /// </summary>
        internal static string msg092 {
            get {
                return ResourceManager.GetString("msg092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kjsdhjfdjhfsjhjhfsd.
        /// </summary>
        internal static string msg093 {
            get {
                return ResourceManager.GetString("msg093", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdkjfhs sdf sdf .
        /// </summary>
        internal static string msg094 {
            get {
                return ResourceManager.GetString("msg094", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es el mensaje 095.
        /// </summary>
        internal static string msg095 {
            get {
                return ResourceManager.GetString("msg095", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este es el mensaje 095.
        /// </summary>
        internal static string msg0951 {
            get {
                return ResourceManager.GetString("msg0951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skdhf.
        /// </summary>
        internal static string msg0952 {
            get {
                return ResourceManager.GetString("msg0952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jellou.
        /// </summary>
        internal static string msg096 {
            get {
                return ResourceManager.GetString("msg096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jhfg jhfg fg fg jhfg jhfgsjfg .
        /// </summary>
        internal static string msg150 {
            get {
                return ResourceManager.GetString("msg150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio {0} ha &quot;sido&quot; iniciado {1}.
        /// </summary>
        internal static string msgIniciaServicio {
            get {
                return ResourceManager.GetString("msgIniciaServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El servicio fulano ha sido iniciado.
        /// </summary>
        internal static string msgIniciaServicio1 {
            get {
                return ResourceManager.GetString("msgIniciaServicio1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola Amigos.
        /// </summary>
        internal static string msgMensaje1 {
            get {
                return ResourceManager.GetString("msgMensaje1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola Amigos.
        /// </summary>
        internal static string msgMensaje11 {
            get {
                return ResourceManager.GetString("msgMensaje11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okl.
        /// </summary>
        internal static string Scrap_103 {
            get {
                return ResourceManager.GetString("Scrap_103", resourceCulture);
            }
        }
    }
}
