/****************************** Module Header ******************************\
* Module Name:  CppDllCOMServerTypeInfo.idl
* Project:      CppDllCOMServer
* Copyright (c) Microsoft Corporation.
* 
* COM is one of the most popular words in Windows world, there are lots of
* technologies are based on it, such as: ActiveX control, WMI, even the super
* star CLR is also based on the COM. 
* This sample demonstrates how to create an in-process COM component by the
* raw interfaces from Win32 DLL project, describes the fundamental concepts
* involved.
* 
* This source is subject to the Microsoft Public License.
* See http://www.microsoft.com/opensource/licenses.mspx#Ms-PL.
* All other rights reserved.
* 
* History:
* * 11/05/2009 02:57 PM Wesley Yao Created
\***************************************************************************/

import "oaidl.idl";
import "ocidl.idl";

// Define ICppSimpleObjectSTA interface
[
    object,
    uuid(0AE6650F-C9D2-46b2-80C8-7FE10654CC93),
    helpstring("ICppSimpleObjectSTA Interface")
]
interface ICppSimpleObjectSTA : IUnknown
{
    HRESULT HelloWorld([out,retval] BSTR* pRet);
    HRESULT GetProcessThreadID([out] LONG* pdwProcessId, [out] LONG* pdwThreadId);
};

// Library statement
[
    uuid(D180D63C-6728-42ce-B953-885CB6E57F01),
    version(1.0),
    helpstring("CppDllCOMServer 1.0 Type Library")
]
library CppDllCOMServerLib
{
    importlib("stdole32.tlb");
    [uuid(3739576F-F27B-4857-9E3E-8BAAA2A030B9)]
    coclass CppSimpleObjectSTA
    {
        [default] interface ICppSimpleObjectSTA;
    };
};