// ATLShellExtCopyHookHandler.idl : IDL source for ATLShellExtCopyHookHandler
//

// This file will be processed by the MIDL tool to
// produce the type library (ATLShellExtCopyHookHandler.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(2B30862A-7572-4AF2-AAC0-7CE3606E803A),
	version(1.0),
	helpstring("ATLShellExtCopyHookHandler 1.0 Type Library")
]
library ATLShellExtCopyHookHandlerLib
{
	importlib("stdole2.tlb");
};
